server:
    port: 1472
spring:
    application:
        name: springbootrest-hospital
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        password: sankar
        url: jdbc:oracle:thin:@//localhost:1521/xe
        username: sankar
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.OracleDialect
                format_sql: true
        show-sql: true
